name: Tests

on:
  push:
    branches: [master]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php:
          - '8.2'
          - '8.1'
    services:
      faktory:
        image: contribsys/faktory:latest
        ports:
          - "7419:7419"
      faktory_with_pwd:
        image: contribsys/faktory:latest
        ports:
          - "7423:7419"
        env:
          FAKTORY_PASSWORD: my_special_password

    name: Tests (PHP ${{ matrix.php }})

    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: none

      - run: composer install
      - run: composer test-ci
